# Generated by Django 5.2 on 2025-04-12 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulos', '0002_perfilcliente_pieza_proveedores_delete_articulos_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pieza',
            new_name='Productos',
        ),
        migrations.RenameModel(
            old_name='PerfilCliente',
            new_name='Usuario',
        ),
    ]
